---
- name: Install docker
  yum:
    name='docker'
    state=latest

- name: Starting Docker
  service:
    name=docker
    state=started
    enabled=yes

- name: Ensure docker-compose is installed and available
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.7.0-rc1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/bin/docker-compose
    mode: 'u+x,g+x'